### ISSUE TITLE
The import-polyfill import fails

### ISSUE THREAD

**Issue by nest-don** [amyisme13/laravel-starter#1]
The yarn build fails with the following.   It works if the vite/dynamic-import-polyfill line is removed however.  

```
yarn build
yarn run v1.22.11
$ NODE_ENV=production vite build
vite v2.5.1 building for production...
✓ 1 modules transformed.
[vite]: Rollup failed to resolve import "vite/dynamic-import-polyfill" from "resources/js/main.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "vite/dynamic-import-polyfill" from "resources/js/main.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/usr/local/forest/services/node_modules/vite/dist/node/chunks/dep-972722fa.js:52196:19)
    at onwarn (/usr/local/forest/services/node_modules/vite/dist/node/chunks/dep-972722fa.js:51981:13)
    at Object.onwarn (/usr/local/forest/services/node_modules/rollup/dist/shared/rollup.js:20515:13)
    at ModuleLoader.handleResolveId (/usr/local/forest/services/node_modules/rollup/dist/shared/rollup.js:19864:26)
    at /usr/local/forest/services/node_modules/rollup/dist/shared/rollup.js:19856:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

**Comment by amyisme13** [comment]
Thanks for noticing.

I look around for this and it looks like the polyfill is removed in the new version of vite (as its not needed anymore in modern browser). I'm not 100% sure why I put that line of code before and as you said just removing it seems to fix it. 

I've updated the code to remove that line of code.

**Comment by nest-don** [comment]
Thank you for providing excellent projects and support.
Much appreciated.
